# Generated by Django 2.1.7 on 2019-03-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Event'),
            preserve_default=False,
        ),
    ]
